'use strict';

/**
 * Comprehensive Kenya delivery zones.
 * Zones: CBD Express (150) · Nairobi Metro (250) · Greater Nairobi (350)
 *        Major Towns (500) · Countrywide (700)
 */
const DELIVERY_ZONES = [
  /* ── CBD Express (KES 150) ─────────────────────────────────────────── */
  { name: 'Nairobi CBD',        zone: 'CBD Express',     fee: 150 },
  { name: 'Westlands',          zone: 'CBD Express',     fee: 150 },
  { name: 'Parklands',          zone: 'CBD Express',     fee: 150 },
  { name: 'Upper Hill',         zone: 'CBD Express',     fee: 150 },
  { name: 'Hurlingham',         zone: 'CBD Express',     fee: 150 },
  { name: 'Ngara',              zone: 'CBD Express',     fee: 150 },
  { name: 'Milimani',           zone: 'CBD Express',     fee: 150 },
  { name: 'Hospital Hill',      zone: 'CBD Express',     fee: 150 },

  /* ── Nairobi Metro (KES 250) ────────────────────────────────────────── */
  { name: 'Eastleigh',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Kilimani',           zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Kileleshwa',         zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Lavington',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Karen',              zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Runda',              zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Gigiri',             zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Muthaiga',           zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Ridgeways',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Spring Valley',      zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Loresho',            zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Woodlands',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Riverside',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Adams Arcade',       zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Ngong Road',         zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Buru Buru',          zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Umoja',              zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Donholm',            zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Komarock',           zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Fedha',              zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Nairobi West',       zone: 'Nairobi Metro',   fee: 250 },
  { name: 'South B',            zone: 'Nairobi Metro',   fee: 250 },
  { name: 'South C',            zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Langata',            zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Buruburu',           zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Madaraka',           zone: 'Nairobi Metro',   fee: 250 },
  { name: 'Woodley',            zone: 'Nairobi Metro',   fee: 250 },

  /* ── Greater Nairobi (KES 350) ──────────────────────────────────────── */
  { name: 'Embakasi',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Embakasi East',      zone: 'Greater Nairobi', fee: 350 },
  { name: 'Embakasi West',      zone: 'Greater Nairobi', fee: 350 },
  { name: 'Embakasi North',     zone: 'Greater Nairobi', fee: 350 },
  { name: 'Embakasi South',     zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kasarani',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Thika Road',         zone: 'Greater Nairobi', fee: 350 },
  { name: 'Ruaka',              zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kikuyu',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Rongai',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Syokimau',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Imara Daima',        zone: 'Greater Nairobi', fee: 350 },
  { name: 'Utawala',            zone: 'Greater Nairobi', fee: 350 },
  { name: 'Mihango',            zone: 'Greater Nairobi', fee: 350 },
  { name: 'Pipeline',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Roysambu',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Zimmerman',          zone: 'Greater Nairobi', fee: 350 },
  { name: 'Githurai',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Githurai 44',        zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kahawa',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kahawa West',        zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kahawa Sukari',      zone: 'Greater Nairobi', fee: 350 },
  { name: 'Ruiru',              zone: 'Greater Nairobi', fee: 350 },
  { name: 'Juja',               zone: 'Greater Nairobi', fee: 350 },
  { name: 'Limuru',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Ngong',              zone: 'Greater Nairobi', fee: 350 },
  { name: 'Athi River',         zone: 'Greater Nairobi', fee: 350 },
  { name: 'Kitengela',          zone: 'Greater Nairobi', fee: 350 },
  { name: 'Mlolongo',           zone: 'Greater Nairobi', fee: 350 },
  { name: 'Mavoko',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Thindigua',          zone: 'Greater Nairobi', fee: 350 },
  { name: 'Membley',            zone: 'Greater Nairobi', fee: 350 },
  { name: 'Wangige',            zone: 'Greater Nairobi', fee: 350 },
  { name: 'Sigona',             zone: 'Greater Nairobi', fee: 350 },
  { name: 'Dagoretti',          zone: 'Greater Nairobi', fee: 350 },

  /* ── Major Towns (KES 500) ──────────────────────────────────────────── */
  { name: 'Mombasa',            zone: 'Major Towns',     fee: 500 },
  { name: 'Nakuru',             zone: 'Major Towns',     fee: 500 },
  { name: 'Kisumu',             zone: 'Major Towns',     fee: 500 },
  { name: 'Eldoret',            zone: 'Major Towns',     fee: 500 },
  { name: 'Thika',              zone: 'Major Towns',     fee: 500 },
  { name: 'Nyeri',              zone: 'Major Towns',     fee: 500 },
  { name: 'Meru',               zone: 'Major Towns',     fee: 500 },
  { name: 'Machakos',           zone: 'Major Towns',     fee: 500 },
  { name: 'Naivasha',           zone: 'Major Towns',     fee: 500 },
  { name: 'Kericho',            zone: 'Major Towns',     fee: 500 },
  { name: 'Embu',               zone: 'Major Towns',     fee: 500 },
  { name: 'Murang\'a',          zone: 'Major Towns',     fee: 500 },
  { name: 'Karatina',           zone: 'Major Towns',     fee: 500 },
  { name: 'Kisii',              zone: 'Major Towns',     fee: 500 },
  { name: 'Kakamega',           zone: 'Major Towns',     fee: 500 },
  { name: 'Bungoma',            zone: 'Major Towns',     fee: 500 },
  { name: 'Kitale',             zone: 'Major Towns',     fee: 500 },
  { name: 'Nanyuki',            zone: 'Major Towns',     fee: 500 },
  { name: 'Nyahururu',          zone: 'Major Towns',     fee: 500 },
  { name: 'Isiolo',             zone: 'Major Towns',     fee: 500 },
  { name: 'Voi',                zone: 'Major Towns',     fee: 500 },

  /* ── Countrywide (KES 700) ──────────────────────────────────────────── */
  { name: 'Malindi',            zone: 'Countrywide',     fee: 700 },
  { name: 'Lamu',               zone: 'Countrywide',     fee: 700 },
  { name: 'Garissa',            zone: 'Countrywide',     fee: 700 },
  { name: 'Wajir',              zone: 'Countrywide',     fee: 700 },
  { name: 'Mandera',            zone: 'Countrywide',     fee: 700 },
  { name: 'Marsabit',           zone: 'Countrywide',     fee: 700 },
  { name: 'Turkana',            zone: 'Countrywide',     fee: 700 },
  { name: 'Lodwar',             zone: 'Countrywide',     fee: 700 },
  { name: 'Kapenguria',         zone: 'Countrywide',     fee: 700 },
  { name: 'Maralal',            zone: 'Countrywide',     fee: 700 },
  { name: 'Moyale',             zone: 'Countrywide',     fee: 700 },
  { name: 'Homa Bay',           zone: 'Countrywide',     fee: 700 },
  { name: 'Siaya',              zone: 'Countrywide',     fee: 700 },
  { name: 'Migori',             zone: 'Countrywide',     fee: 700 },
  { name: 'Bomet',              zone: 'Countrywide',     fee: 700 },
  { name: 'Narok',              zone: 'Countrywide',     fee: 700 },
  { name: 'Kajiado',            zone: 'Countrywide',     fee: 700 },
  { name: 'Kwale',              zone: 'Countrywide',     fee: 700 },
  { name: 'Kilifi',             zone: 'Countrywide',     fee: 700 },
  { name: 'Tana River',         zone: 'Countrywide',     fee: 700 },
  { name: 'Taita Taveta',       zone: 'Countrywide',     fee: 700 },
  { name: 'Makueni',            zone: 'Countrywide',     fee: 700 },
  { name: 'Kitui',              zone: 'Countrywide',     fee: 700 },
  { name: 'Mwingi',             zone: 'Countrywide',     fee: 700 },
  { name: 'Kirinyaga',          zone: 'Countrywide',     fee: 700 },
  { name: 'Nyandarua',          zone: 'Countrywide',     fee: 700 },
  { name: 'Laikipia',           zone: 'Countrywide',     fee: 700 },
  { name: 'Samburu',            zone: 'Countrywide',     fee: 700 },
  { name: 'Trans Nzoia',        zone: 'Countrywide',     fee: 700 },
  { name: 'Uasin Gishu',        zone: 'Countrywide',     fee: 700 },
  { name: 'Elgeyo Marakwet',    zone: 'Countrywide',     fee: 700 },
  { name: 'Nandi',              zone: 'Countrywide',     fee: 700 },
  { name: 'Baringo',            zone: 'Countrywide',     fee: 700 },
  { name: 'West Pokot',         zone: 'Countrywide',     fee: 700 },
  { name: 'Busia',              zone: 'Countrywide',     fee: 700 },
  { name: 'Vihiga',             zone: 'Countrywide',     fee: 700 },
];

module.exports = DELIVERY_ZONES;
